name: Build legate.core documentation

on:
  push:
    branches:
      - "pull-request/[0-9]+"
      - "branch-*"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  COMMIT: ${{ github.event.pull_request.head.sha || github.sha }}
  PROJECT: github-core-ci
  REF: ${{ github.event.pull_request.head.ref || github.ref }}
  EVENT_NAME: ${{ github.event_name }}
  LABEL: ${{ github.event.pull_request.head.label }}
  REPO_URL: ${{ github.event.pull_request.head.repo.html_url || github.event.repository.html_url }}
  ARTIFACTS_DIR: "${{ github.workspace }}/.artifacts"
  ARTIFACT_NAME: "legate-core-docs"
  # Prevent output buffering
  PYTHONUNBUFFERED: 1

jobs:
  build:
    permissions:
      id-token: write # This is required for configure-aws-credentials
      contents: read  # This is required for actions/checkout
      packages: write # This is required to push docker image to ghcr.io

    runs-on: ${{ contains(github.repository, 'nv-legate/legate.core') && 'linux-amd64-cpu16' || 'ubuntu-latest' }}

    defaults:
      run:
        shell: bash

    container:
      options: -u root
      image: condaforge/miniforge3:latest
      
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      ####################################
      # Actual build process starts here #
      ####################################

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - if: github.repository_owner == 'nv-legate'
        name: Get AWS credentials for sccache bucket
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-2
          role-duration-seconds: 28800 # 8 hours
          role-to-assume: arn:aws:iam::279114543810:role/gha-oidc-nv-legate

      - name: Build Documentation
        run: |
          /bin/bash -c "cd $(pwd) && mkdir -p $ARTIFACTS_DIR && ./continuous_integration/scripts/build-legate docs"

      - name: Upload documentation
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACTS_DIR }}